#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BASE_DOCKERFILE="$ROOT_DIR/Dockerfile"
IKENTIC_DOCKERFILE="$ROOT_DIR/Dockerfile.ikentic"
MODE="${1:-write}"

if [[ ! -f "$BASE_DOCKERFILE" ]]; then
  echo "Missing base Dockerfile: $BASE_DOCKERFILE" >&2
  exit 1
fi

if [[ "$MODE" != "write" && "$MODE" != "--check" ]]; then
  echo "Usage: bash ikentic/scripts/sync-dockerfile.sh [--check]" >&2
  exit 2
fi

generated="$(mktemp)"
trap 'rm -f "$generated"' EXIT

cat >"$generated" <<'EOF'
# syntax=docker/dockerfile:1.7
# Generated by ikentic/scripts/sync-dockerfile.sh from Dockerfile.
# Keep IKENTIC-specific deltas here only:
#   1) BuildKit secret mount for pnpm install
#   2) Remove .npmrc before build steps to avoid token expansion warnings
EOF

sed '1{/^# syntax=docker\/dockerfile:/d;}' "$BASE_DOCKERFILE" >>"$generated"

python3 - "$generated" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()

install_old = "RUN pnpm install --frozen-lockfile"
install_new = (
    "RUN --mount=type=secret,id=node_auth_token,required=false \\\n"
    "    NODE_AUTH_TOKEN=\"$(cat /run/secrets/node_auth_token 2>/dev/null || true)\" \\\n"
    "    pnpm install --frozen-lockfile"
)

copy_old = "COPY . .\nRUN pnpm build"
copy_new = (
    "COPY . .\n"
    "# The auth-aware .npmrc is only needed for dependency install above.\n"
    "# Remove it so later pnpm invocations do not warn about missing NODE_AUTH_TOKEN.\n"
    "RUN rm -f /app/.npmrc\n"
    "RUN pnpm build"
)

if install_old not in text:
    raise SystemExit("ikentic sync-dockerfile: expected pnpm install line not found")
if copy_old not in text:
    raise SystemExit("ikentic sync-dockerfile: expected COPY/build block not found")

text = text.replace(install_old, install_new, 1)
text = text.replace(copy_old, copy_new, 1)
path.write_text(text)
PY

if [[ "$MODE" == "--check" ]]; then
  if ! diff -u "$IKENTIC_DOCKERFILE" "$generated"; then
    echo "" >&2
    echo "Dockerfile.ikentic is out of sync with Dockerfile." >&2
    echo "Run: bash ikentic/scripts/sync-dockerfile.sh" >&2
    exit 1
  fi
  echo "Dockerfile.ikentic is in sync"
  exit 0
fi

mv "$generated" "$IKENTIC_DOCKERFILE"
echo "Updated $IKENTIC_DOCKERFILE"
