#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_DOCKERFILE="$ROOT_DIR/Dockerfile"
IKENTIC_DOCKERFILE="$ROOT_DIR/Dockerfile.ikentic"

if [[ ! -f "$BASE_DOCKERFILE" ]]; then
  echo "Missing base Dockerfile: $BASE_DOCKERFILE" >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

cat >"$tmp" <<'EOF'
# syntax=docker/dockerfile:1.7
# Generated by scripts/sync-ikentic-dockerfile.sh from Dockerfile.
# Keep IKENTIC-specific deltas here only:
#   1) BuildKit secret mount for pnpm install
#   2) Remove .npmrc before build steps to avoid token expansion warnings
EOF

sed '1{/^# syntax=docker\/dockerfile:/d;}' "$BASE_DOCKERFILE" >>"$tmp"

python3 - "$tmp" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()

install_old = "RUN pnpm install --frozen-lockfile"
install_new = (
    "RUN --mount=type=secret,id=node_auth_token,required=false \\\n"
    "    NODE_AUTH_TOKEN=\"$(cat /run/secrets/node_auth_token 2>/dev/null || true)\" \\\n"
    "    pnpm install --frozen-lockfile"
)

extra_old = (
    "RUN if [ -n \"$OPENCLAW_DOCKER_NPM_PACKAGES\" ]; then \\\n"
    "      npm install --no-save $OPENCLAW_DOCKER_NPM_PACKAGES && \\\n"
    "      npm cache clean --force; \\\n"
    "    fi"
)
extra_new = (
    "RUN --mount=type=secret,id=node_auth_token,required=false \\\n"
    "    NODE_AUTH_TOKEN=\"$(cat /run/secrets/node_auth_token 2>/dev/null || true)\" \\\n"
    "    if [ -n \"$OPENCLAW_DOCKER_NPM_PACKAGES\" ]; then \\\n"
    "      npm install --no-save $OPENCLAW_DOCKER_NPM_PACKAGES && \\\n"
    "      npm cache clean --force; \\\n"
    "    fi"
)

copy_old = "COPY . .\nRUN pnpm build"
copy_new = (
    "COPY . .\n"
    "# The auth-aware .npmrc is only needed for dependency install above.\n"
    "# Remove it so later pnpm invocations do not warn about missing NODE_AUTH_TOKEN.\n"
    "RUN rm -f /app/.npmrc\n"
    "RUN pnpm build"
)

if install_old not in text:
    raise SystemExit("sync-ikentic-dockerfile: expected pnpm install line not found")
if extra_old not in text:
    raise SystemExit("sync-ikentic-dockerfile: expected OPENCLAW_DOCKER_NPM_PACKAGES block not found")
if copy_old not in text:
    raise SystemExit("sync-ikentic-dockerfile: expected COPY/build block not found")

text = text.replace(install_old, install_new, 1)
text = text.replace(extra_old, extra_new, 1)
text = text.replace(copy_old, copy_new, 1)
path.write_text(text)
PY

mv "$tmp" "$IKENTIC_DOCKERFILE"
echo "Updated $IKENTIC_DOCKERFILE"
